import Head from 'next/head'
import Header from "../components/Header"
import Results from "../components/Results"
import movieRequests from "../utils/movieRequests";

export default function Home({ results }) {
    return (
        <div className="container-fluid mx-auto">
   
          <Head>
             <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
          <main className=" conatiner mx-auto">
              <Results results={results} />
          </main>
      </div>
    )
}

export async function getServerSideProps(context) {
    const genre = context.query.genre || "fetchTrending";
    const request = await fetch(`https://api.themoviedb.org/3${movieRequests[genre].url}`).then((response) => response.json());

    return {
        props: {
            results: request.results,
        },
    };
}